title: noble exchange
author: kayode96-max
email: olukayodeusman406@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  instant pzy....quick reply awesome deals and rewards
  line in _config.yml. It will appear in your document head meta (btc...giftcard...itunes..googleplay...steam..amazon) and in your feed.xml site description.

# social links
twitter_username: abdulla48669027 # DO NOT include the @ character, or else the build will fail!
github_username:  kayode96-max # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
